services:
  bios-db:
    image: mysql:latest
    ports:
      - "3307:3306"
    restart: always
    environment:
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: bios_db